services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes: 
      - qdrant_data:/qdrant/storage # For persistent storage
    restart: unless-stopped # Ensure Qdrant restarts if it crashes

  qdrant-interactor:
    image: qdrant-interactor:latest
    build:
      context: ./packages/qdrant-interactor # Build context for your Python service
      dockerfile: Dockerfile            # Assuming you'll have a Dockerfile here
    container_name: qdrant-interactor
    ports:
      - "9000:9000" # Or 50051:50051 if using gRPC
    depends_on:
      - qdrant # Ensure Qdrant starts before the Python service
    environment:
      # Pass Qdrant host to the Python service
      # 'qdrant' is the service name in docker-compose, which resolves to its IP
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333 # Or 6334 for gRPC
    # Add rate limiting variables here if needed
    # - EMBEDDING_CONCURRENCY=5

  web-crawler:
    image: web-crawler:latest
    build:
      context: ./packages/web-crawler
      dockerfile: Dockerfile
    environment:
      - STARTING_URL=https://web.cs.toronto.edu/people/faculty-directory
      - CRAWL_DEPTH=10

  chatbot:
    image: chatbot:latest
    build:
      context: ./packages/chatbot
      dockerfile: Dockerfile
    container_name: chatbot
    ports:
      - "9001:9001" # Expose the chatbot service on port 9001
    depends_on:
      - qdrant-interactor # Ensure the Python service is ready before starting the chatbot
    environment:
      - QDRANT_INTERACTOR_URL=http://qdrant-interactor:9000
      - OPENAI_API_KEY=${OPENAI_API_KEY}


  web-client:
    image: web-client:latest
    build:
      context: ./packages/web-client
      dockerfile: Dockerfile
    ports:
      - "9090:80"  # Map host port 8080 to container port 80 (Nginx default)
    depends_on:
      - qdrant-interactor # Ensure the Python service is ready before starting the web client
    environment:
      - VITE_CHATBOT_URL=https://web-crawler-chatbot.baleinegris.site/query # URL for the Python service

# Define the named volume for Qdrant data
volumes:
  qdrant_data:
    # driver: local # Default driver, explicitly stating it
